name: Windows OpenPegasus Build

on: 
  - workflow_dispatch

jobs:
  openPegasusMatrix:
    strategy:
      matrix:
        commands: ['make world']

    runs-on: windows-latest
    steps:
      - name: Matrix parameters
        run:  |
          echo "Matrix run"
          echo "Command: ${{matrix.commands}}"

      - name: Install dependencies
        run:  |
          choco install make -y --no-progress
          choco install openssl -y --no-progress

      - name: Install dependencies
        run:  openssl version -a     
          
      - name: Configure OpenPegasus
        shell: powershell
        run: |
          echo "Step Configure OpenPegasus for build and test common config"
          Write-Output "PEGASUS_ROOT=${env:GITHUB_WORKSPACE}\pegasus" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          Write-Output "PEGASUS_HOME=${env:GITHUB_WORKSPACE}\work" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          Write-Output "PEGASUS_PLATFORM=WIN32_IX86_MSVC" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          Write-Output "PEGASUS_ENABLE_SLP=false" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          Write-Output "PEGASUS_TMP=${env:GITHUB_WORKSPACE}\temp" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          Write-Output "${env:GITHUB_WORKSPACE}\work\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Testing variables
        shell: cmd
        run: |
            echo "testing variables"
            echo %PEGASUS_ROOT%
            echo %PEGASUS_HOME%
            echo %PEGASUS_PLATFORM%

      - name: Delete Unwanted Link to Stop It From Interfering
        shell: bash
        run: |
              rm /usr/bin/link.exe

      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build commands
        shell: cmd
        working-directory: pegasus
        run: ${{matrix.commands}}
